AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sends log data from CloudWatch Logs and S3 to New Relic Infrastructure (Cloud integrations) and New Relic Logging.
Parameters:
  NewRelicLicenseKey:
    Type: String
    Description: Your NewRelic license key. You may omit it when deploying the function.
    Default: "YOUR_LICENSE_KEY"
  Bucket:
    Type: String
    Description: The bucket where the newrelic-log-ingestion.zip is placed
  Key:
    Type: String
    Description: The key of newrelic-log-ingestion.zip

Resources:
  NewRelicLogIngestionFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: python3.6
      Handler: function.lambda_handler
      CodeUri:
        Bucket: !Ref Bucket
        Key: !Ref Key
      FunctionName: newrelic-log-ingestion
      Timeout: 30
      Environment:
        Variables: 
          LICENSE_KEY: !Ref NewRelicLicenseKey

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref NewRelicLogIngestionFunction
      Action: lambda:InvokeFunction
      Principal: !Sub logs.${AWS::Region}.amazonaws.com
      SourceArn: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*

Outputs:
  LambdaArn:
    Description: The arn of the lambda
    Value: 
     Fn::GetAtt:
          - NewRelicLogIngestionFunction
          - Arn
